kind: Service
apiVersion: v1
metadata:
  name: {{ .PostgresqlService }}
  namespace: {{ .ApplicationNamespace }}
  annotations:
    template.openshift.io/expose-uri: postgres://{.spec.clusterIP}:{.spec.ports[?(.name=="postgresql")].port}
  labels:
    app: {{ .ApplicationName }}
spec:
  ports:
  - name: postgresql
    protocol: TCP
    port: 5432
    targetPort: 5432
    nodePort: 0
  selector:
    name: {{ .PostgresqlDeployment }}
  type: ClusterIP
  sessionAffinity: None