kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .PostgresqlPvc }}
  namespace: {{ .ApplicationNamespace }}
  labels:
    app: {{ .ApplicationName }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .PostgresqlPvcCapacity }}