apiVersion: rhpam.integreatly.org/v1alpha1
kind: RhpamDev
metadata:
  name: example-rhpamdev
spec:
  domain: apps.mycluster.com
  config:
    database:
      persistentVolumeCapacity: "1Gi"
      maxConnections: "100"
      sharedBuffers: "32MB"
      maxPreparedTransactions: "100"
      memoryLimit: "512Mi"
    businessCentral:
      persistentVolumeCapacity: "1Gi"
      cpuRequest: "200m"
      cpuLimit: "2000m"
      memoryRequest: "1Gi"
      memoryLimit: "3Gi"
      gcMaxMetaSize: "500"
      kieMbeans: "enabled"
      javaOptsAppend: "-Dorg.uberfire.nio.git.ssh.algorithm=RSA"
    kieServer:
      cpuRequest: "200m"
      cpuLimit: "1000m"
      memoryRequest: "1Gi"
      memoryLimit: "3Gi"
      gcMaxMetaSize: "500"
      kieMbeans: "enabled"
      kieServerId: "kieserver-dev"
      filterClasses: "true"
      bypassAuthUser: "false"
